### ISSUE TITLE
String Queue vs. Object Queue

### ISSUE THREAD

**Issue by xiaju** [dodecahedronal/A1-part2#2]
As per the assignment instructions we need to be able to support explicit string queues as well as explicit object queues. I believe this could be done with method overloading, subclassing or another method, but the current interface doesn't support it.

see piazza post:
https://piazza.com/class/k51bluky59n2jr?cid=331

**Comment by dodecahedronal** [comment]
The logic behind the queue is that you declare a Queue type variable, and then perform actions, such as dequeue or enqueue. When you declare the queue you don’t need to restrict the type of objects in the queue, besides which, strings are objects. The code can handle both Objects and Strings the way it’s currently written. It’s more efficient this way.
