### ISSUE TITLE
Rename myString.h to string.h

### ISSUE THREAD

**Issue by xiaju** [dodecahedronal/A1-part2#3]
Could we rename myString.h to string.h so it's consistent with the naming other people used? I'd like to be able to reuse my string.h file from map and array for queue as well.

**Comment by dodecahedronal** [comment]
Oh, sorry! I originally named it myString.h, because for some reason, my IDE couldn't handle both an #include<string.h> and #include"string.h". I've changed it in this [commit](https://github.com/dodecahedronal/A1-part2/commit/e6e360503e7900e486c0d8b3dc81e178dfdd1f23).
