### ISSUE TITLE
Remove Node class

### ISSUE THREAD

**Issue by xiaju** [dodecahedronal/A1-part2#4]
I'm not sure why there's a node class in the file, but could you remove it? I don't think it's necessary. There are also variables in the queue interface that don't need to be there

**Comment by austenke** [comment]
+1, nodes are an implementation detail. At the very least the fields should be removed.

**Comment by dodecahedronal** [comment]
Did a complete overhaul of the code. Got rid of nodes in the process so that implementation can be left up to you. [Commit](https://github.com/dodecahedronal/A1-part2/commit/073a7f13f462aaccb21ea8df4db647dfb6007240).
